github.com:
    users:
        fourtytwo42:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: fourtytwo42
